### ISSUE TITLE
Portainer not able to use docker-compose file v3

### ISSUE THREAD

**Issue by jikelmon** [evertramos/docker-portainer-letsencrypt#4]
Thank you very much for your docker repos with reverse proxy. They are awesome!

I have started using docker not long ago so this could potential be a silly question. Sadly i encountered a misbehaviour in my installation and wanted to ask for assistance:

I am not able to start docker-compose files greater v2. Portainer says "Only Compose file format version 2 is supported at the moment." The official portainer demo does allow me to use v3 as stated in the git.

I used your script and have version 1.19.1 of portainer installed successfully. Engine 18.06.1-ce is used with API v1.38 via a local socket connection.

Could you point me into the right direction how to resolve my problem?

Thank you very much and best regards.

**Comment by evertramos** [comment]
Hello @jikelmon,

Thanks for using our scripts!

This is probably a limitation on Portainer for this latest version... not sure how to help you on that...

If you provide the logs in the portainer github issue you might find some answers for that.

**Comment by jikelmon** [comment]
Hi @evertramos,

i took a closer look onto the demo intallation of portainer and experienced that they are using docker-swarm, so my bad.

Best regards
