### ISSUE TITLE
Portainer not running

### ISSUE THREAD

**Issue by LucaMoiana** [evertramos/docker-portainer-letsencrypt#5]
Noob in training with docker:
Docker VPS on Digital Ocean
did follow instructions on docker-compose-letsencrypt-nginx-proxy-companion then run
./test_start_ssl.sh mydomain, www.mydomain
./test_start_ssl.sh portainer.mydomain
./stop_test 
followed instructions on docker-portainer-letsencrypt but when I go to portainer.mydomain i get "ERR_NAME_NOT_RESOLVED"
I have a cert named portainer.mydomain on certs folder and I did point to that on .env file
If I read the logs I see

> ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new authz :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/

what am I doing wrong?

**Comment by evertramos** [comment]
Hello @LucaMoiana!

First you start the webproxy... don´t need to test it with the "test_start"... if you test it should only show an empty page saying its ok!

After that you stop the test (if you started) and configure this repo with the information in the env file (of this repo) including the domain name and run the "start.sh" script of this repo.

That should do the trick.

Please try again and do not delete the ssl certificates.. letsencrypt have limits on the requests it seems you have created a lot of ssl certificates to reach this limit.

**Comment by LucaMoiana** [comment]
thanks again for yuor help.
Still not getting it, do I have to setup something on my DigitalOcean VPS networking panel in order to get mydomain (without www) available or any other (subdomain.mydomain) available?

**Comment by LucaMoiana** [comment]
I did create a wild card subdomain in Digital Ocean, following a tutorial.
killed and reinstalled all the dockers, following your isntruction. Situation is:
I can see https://officinecartografiche.net on Chrome
If I go to https://www.officinecartografiche.net on Chrome I get NET::ERR_CERT_COMMON_NAME_INVALID
If I go to https://portainer.officinecartografiche.net I get DNS_PROBE_FINISHED_NXDOMAIN

What am I doing wrong?

**Comment by evertramos** [comment]
Hello @LucaMoiana!

This repo was supposed to work with LetsEncrypt Certificates autogenerated by https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion, which does not cover the wild card certificate... and it auto generates its own certificates... 

If you have copied the certificate to the "nginx" certs folder you should be able to add all these three domains into your $DOMAIN variable and see if it is using the correct certificate... 

I am not sure where did they do, but there were a few discussions around it in these repos: https://github.com/jwilder/nginx-proxy and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion. 

We are working in a new proxy to fix a few things... it´s on the way for next year, but still far from production.
