### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Geraldf** [evertramos/docker-portainer-letsencrypt#6]
I am using your docker-compose-letsencrypt-nginx-proxy-companion together with this portioner project. When it is running and start the website (https://portianer.xx.yy) I do get the ERR_TOO_MANY_REDIRECTS error in Chrome. In safari I get a similar message regarding the high amount of redirects. 

> server {
	server_name portainer.xxx.yy;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name portainer.xxx.yy;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://portainer.xxx.yy;
	}
}

This looks like the https:// request gets redirected to the http:// side, and this returns back to https://

**Comment by evertramos** [comment]
Hello @Geraldf,

Could you post your compose file for portainer?
