### ISSUE TITLE
Portainer goes down when using Docker API

### ISSUE THREAD

**Issue by catalinroweb** [evertramos/docker-portainer-letsencrypt#7]
# Error description:
So, i connected to my docker env using TLS config Domain:Port (not IP, i used domain because IP is dynamic)
As example i will use "example.com:1234"
After i add a container ("nginx:alpine in my case) which points to my domain ("example.com"), the Portainer endpoint is no more accesible, is down.

# Steps to reproduce
Connect to a docker machine using Docker API using Domain:Port.
Add nginx container which points to used domain and deploy it.
Refresh portainer

# Expected result
Portained endpoints will be accesible in order to show all my running images, volumesc, etc

# Error result
Portainer endpoint is "down"

# Comments

**Comment by catalinroweb** [comment]
Ok, thanks. I will fill a bug report to Portainer.

**Comment by catalinroweb** [comment]
If i use the real ip, is working. I still think is a proxy problem.

**Comment by evertramos** [comment]
@catalinroweb 

I didn´t get it... 

please post your compose file for proxy, for portainer, show some logs on the request on the nginx-proxy.. and logs on portainer I might be able to help you with. I could not reproduce what you post in first place... didn´t even understand. sorry
